--lord key from db/agent_subtypes_tables
--unit group name from localisation table
Supply_lines_rework.group_discount = {
  --empire
    ["emp_karl_franz-srw_emp_greatswords"] = -2,
    ["emp_karl_franz-srw_emp_reiksguard"] = -2,
    ["wh2_dlc13_emp_cha_markus_wulfhart_0-srw_emp_huntsmen"] = -2,
    ["wh2_dlc13_emp_cha_markus_wulfhart_0-srw_all_archers"] = -2,
    ["dlc04_emp_volkmar-srw_emp_knights_emp"] = -2,
    ["emp_balthasar_gelt-srw_all_artillery"] = -1,
    ["emp_balthasar_gelt-srw_emp_artillery_wagon"] = -1,
    --cult of ulric
    ["ulric_grandmaster-srw_emp_knight_white_wolf"] = -2,
    ["ulric_ar_ulric-srw_emp_ulric_cult"] = -2,
    ["ulric_ar_ulric-srw_emp_knight_white_wolf"] = -2,
    --mixu
    ["emp_marius_leitdorf-srw_emp_knights_emp"] = -2,
    ["emp_marius_leitdorf-srw_emp_blazing_sun"] = -2,
    ["emp_marius_leitdorf-srw_emp_reiksguard"] = -2,
    ["emp_wolfram_hertwig-srw_emp_knights_emp"] = -2,
    ["emp_wolfram_hertwig-srw_emp_blazing_sun"] = -2,
    ["emp_wolfram_hertwig-srw_emp_reiksguard"] = -2,
    ["emp_aldebrand_ludenhof-srw_emp_handgunners"] = -2,
    ["emp_aldebrand_ludenhof-srw_elite_hangunners"] = -2,
    --boris
    ["dlc03_emp_boris_todbringer-srw_all_archers"] = -2,
    ["dlc03_emp_boris_todbringer-srw_emp_crossbowmen"] = -2,
    ["dlc03_emp_boris_todbringer-srw_emp_flagellants"] = -2,
    ["dlc03_emp_boris_todbringer-srw_emp_free_company"] = -2,
    ["dlc03_emp_boris_todbringer-srw_emp_halberdiers"] = -2,
    ["dlc03_emp_boris_todbringer-srw_emp_handgunners"] = -2,
    ["dlc03_emp_boris_todbringer-srw_emp_swordsmen"] = -2,
    ["dlc03_emp_boris_todbringer-srw_all_spearmen"] = -2,

    ["wh_main_emp_cha_eldred-srw_all_archers"] = -1,
    ["wh_main_emp_cha_eldred-srw_emp_crossbowmen"] = -1,
    ["wh_main_emp_cha_eldred-srw_emp_flagellants"] = -1,
    ["wh_main_emp_cha_eldred-srw_emp_free_company"] = -1,
    ["wh_main_emp_cha_eldred-srw_emp_halberdiers"] = -1,
    ["wh_main_emp_cha_eldred-srw_emp_handgunners"] = -1,
    ["wh_main_emp_cha_eldred-srw_emp_swordsmen"] = -1,
    ["wh_main_emp_cha_eldred-srw_all_spearmen"] = -1,
    ["wh_main_emp_cha_eldred-srw_emp_greatswords"] = -1,
    ["emp_theoderic_gausser-srw_emp_free_company"] = -2,
    ["emp_valmir_von_raukov-srw_emp_halberdiers"] = -2,
    ["emp_valmir_von_raukov-srw_all_spearmen"] = -2,
    ["emp_alberich_haupt_anderssen-srw_all_archers"] = -2,
    ["emp_alberich_haupt_anderssen-srw_emp_huntsmen"] = -2,
    ["emp_helmut_feuerbach-srw_emp_taal_cult"] = -2,
    ["emp_helmut_feuerbach-srw_emp_rhya"] = -2,
  --dwarfs
    ["dwf_ungrim_ironfist-srw_dwf_slayers"] = -2,
    ["dwf_thorgrim_grudgebearer-srw_dwf_longbeards"] = -2,
    ["dwf_thorgrim_grudgebearer-srw_dwf_hammerers"] = -2,
    ["wh2_dlc17_dwf_thorek-srw_dwf_artillery_classic"] = -2,
    ["wh2_dlc17_dwf_thorek-srw_dwf_quarrellers"] = -2,
    --mods
    ["wh_main_dwf_cha_greybeard-srw_dwf_flying_machine"] = -2,
    ["wh_main_dwf_cha_greybeard-srw_dwf_land_machine"] = -2,
    ["dwf_kraka_drak-srw_dwf_huskarls"] = -2,
    ["dwf_sven_hasselfriesian-srw_dwf_warriors"] = -2,
    ["dwf_sven_hasselfriesian-srw_dwf_artillery_classic"] = -2,
    ["dwf_sven_hasselfriesian-srw_dwf_artillery_gun"] = -2,
    ["dwf_sven_hasselfriesian-srw_dwf_artillery_fire"] = -2,
    ["dwf_alrik_ranulfsson-srw_dwf_longbeards"] = -2,
    ["dwf_brokk_ironpick-srw_dwf_irondrakes"] = -2,
    ["dwf_brokk_ironpick-srw_dwf_flying_machine"] = -2,
    ["dwf_brokk_ironpick-srw_dwf_artillery_fire"] = -2,
    ["dwf_rorek_granitehand-srw_dwf_ironbreakers"] = -2,
    ["dwf_rorek_granitehand-srw_dwf_miners"] = -2,
    ["dwf_kazador_dragonslayer-srw_dwf_ironbreakers"] = -2,
    ["dwf_kazador_dragonslayer-srw_dwf_miners"] = -2,
    ["dwf_bloodline_grimm_burloksson-srw_dwf_flying_machine"] = -2,
  --greekskins
    ["grn_grimgor_ironhide-srw_grn_black_orcs"] = -2,
    ["grn_grimgor_ironhide-srw_grn_big_uns"] = -2,
    ["grn_grimgor_ironhide-srw_grn_big_uns_boar"] = -2,
    ["grn_azhag_the_slaughterer-srw_grn_wyverns"] = -2,
    ["dlc06_grn_skarsnik-srw_grn_night_goblins"] = -2,
    ["dlc06_grn_skarsnik-srw_grn_goblins"] = -2,
    ["dlc06_grn_skarsnik-srw_grn_goblin_spider"] = -2,
    ["dlc06_grn_skarsnik-srw_grn_goblin_wolves"] = -2,
    ["dlc06_grn_wurrzag_da_great_prophet-srw_grn_savage"] = -2,
    ["dlc06_grn_wurrzag_da_great_prophet-srw_grn_savage_boar"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-srw_grn_wagon"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-srw_grn_goblins"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-srw_grn_goblin_spider"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-srw_grn_goblin_wolves"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-srw_grn_big_uns_boar"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-srw_grn_savage_boar"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-srw_grn_savage"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-srw_grn_big_uns"] = -2,
    ["wh2_dlc15_grn_goblin_great_shaman_raknik-srw_grn_goblin_spider"] = -2,
    ["wh2_dlc15_grn_goblin_great_shaman_raknik-srw_grn_arachnarok"] = -2,
    --mods
    ["grn_gorbad_ironclaw-srw_grn_big_uns_boar"] = -2,
    ["grn_gorbad_ironclaw-srw_grn_big_uns"] = -2,
    ["ws_grn_grak_beastbasha-srw_grn_arachnarok"] = -2,
    ["ws_grn_grak_beastbasha-srw_grn_giants"] = -2,
    ["ws_grn_grak_beastbasha-srw_grn_idols"] = -2,
    ["ws_grn_grak_beastbasha-srw_grn_other_monsters"] = -2,
    ["ws_grn_grak_beastbasha-srw_grn_wyverns"] = -2,
    ["ws_grn_grak_beastbasha-srw_all_trolls"] = -2,
    ["ws_grn_grak_beastbasha-srw_grn_savage"] = -2,
    ["ws_grn_grak_beastbasha-srw_def_hydra"] = -2,
    ["ws_grn_grak_beastbasha-srw_grn_savage_boar"] = -2,
    ["grn_gorfang_rotgut-srw_grn_big_uns_boar"] = -2,
    ["grn_gorfang_rotgut-srw_grn_big_uns"] = -2,
    ["grn_gorfang_rotgut-srw_all_chariots"] = -2,
  --vcounts
    ["vmp_mannfred_von_carstein-srw_vmp_black_knights"] = -2,
    ["dlc04_vmp_helman_ghorst-srw_vmp_grave_guard"] = -2,
    ["pro02_vmp_isabella_von_carstein-srw_vmp_vampiress"] = -2,
    ["wh2_dlc11_vmp_bloodline_lahmian-srw_vmp_lahmian"] = -2,
  --norsca
    ["wh_dlc08_nor_wulfrik-srw_nor_marauders"] = -2,
    ["wh_dlc08_nor_wulfrik-srw_nor_berserkers"] = -2,
    ["wh_dlc08_nor_wulfrik-srw_nor_mammoths"] = -2,
    ["wh_dlc08_nor_throgg-srw_all_trolls"] = -2,
    ["nor_egil_styrbjorn-srw_nor_berserkers"] = -2,
    ["nor_egil_styrbjorn-srw_nor_skinwolves"] = -2,
    ["thm_skeggi_losterikson-srw_nor_marauders"] = -2,
    ["thm_skeggi_losterikson-srw_nor_dinos"] = -2,
  --wood elves
    ["dlc05_wef_orion-srw_wef_stag_cav"] = -2,
    ["dlc05_wef_durthu-srw_wef_trees"] = -2,
    ["wh2_dlc16_wef_sisters_of_twilight-srw_all_archers"] = -2,
    ["wh2_dlc16_wef_sisters_of_twilight-srw_all_dragons"] = -2,
    ["wh2_dlc16_wef_sisters_of_twilight-srw_wef_hawks"] = -2,
    ["wh2_dlc16_wef_drycha-srw_wef_trees"] = -2,
    --mixu
    ["wef_wychwethyl-srw_wef_wardancers"] = -2,
  --hight elves
    ["wh2_main_hef_tyrion-srw_all_archers"] = -2,
    ["wh2_main_hef_tyrion-srw_all_spearmen"] = -2,
    ["wh2_main_hef_tyrion-srw_hef_swordsmen"] = -2,
    ["wh2_main_hef_tyrion-srw_hef_sea_guard"] = -1,
    ["wh2_main_hef_tyrion-srw_hef_silver_helms"] = -2,
    ["wh2_dlc10_hef_alith_anar-srw_hef_stealth_archers"] = -2,
    ["wh2_main_hef_prince_alastar-srw_hef_lions"] = -2,
    ["wh2_main_hef_prince_alastar-srw_hef_lion_chariots"] = -2,
    ["wh2_dlc10_hef_alarielle-srw_hef_avelorn"] = -2,
    ["wh2_main_hef_teclis-srw_hef_phoenixes"] = -2,
    ["wh2_main_hef_teclis-srw_hef_swordmasters"] = -2,
    ["wh2_dlc15_hef_imrik-srw_hef_dragon_princes"] = -2,
    ["wh2_dlc15_hef_imrik-srw_all_dragons"] = -2,
    ["wh2_dlc15_hef_eltharion-srw_hef_mistwalkers"] = -2,
    --mods
    ["hef_korhil-srw_hef_lions"] = -2,
    ["hef_korhil-srw_hef_lion_chariots"] = -2,
    ["hef_belannaer-srw_hef_swordmasters"] = -2,
    ["hef_bloodline_caradryan-srw_hef_phoenixes"] = -2,
    ["hef_bloodline_caradryan-srw_hef_phoenix_guard"] = -2,
    ["AK_aislinn-srw_hef_sea_company"] = -2,
    ["AK_aislinn-srw_hef_sea_guard"] = -2,
  --dark elves
    ["wh2_main_def_malekith-srw_def_black_guard"] = -2,
    ["wh2_main_def_malekith-srw_def_darkshards"] = -2,
    ["wh2_main_def_malekith-srw_all_spearmen"] = -2,
    ["wh2_dlc11_def_lokhir-srw_def_corsairs"] = -2,
    ["wh2_dlc10_def_crone_hellebron-srw_def_witch_elves"] = -2,
    ["wh2_dlc10_def_crone_hellebron-srw_def_sisters"] = -2,
    ["wh2_dlc14_def_malus_darkblade-srw_def_cold_one_chariot"] = -2,
    ["wh2_dlc14_def_malus_darkblade-srw_def_cold_one"] = -2,
    ["wh2_twa03_def_rakarth-srw_all_dragons"] = -2,
    ["wh2_twa03_def_rakarth-srw_def_hydra"] = -2,
    ["wh2_twa03_def_rakarth-srw_def_monsters"] = -2,
    ["wh2_twa03_def_rakarth-srw_def_medusa"] = -2,
    ["wh2_twa03_def_rakarth-srw_all_manticore"] = -2,
    --mods
    ["def_tullaris_dreadbringer-srw_def_witch_elves"] = -2,
    ["def_tullaris_dreadbringer-srw_def_executioners"] = -2,
    ["volilosh-srw_def_darkshards"] = -2,
    ["volilosh-srw_def_shades"] = -2,
    ["def_hag_queen_malida-srw_def_witch_elves"] = -2,
  --skaven
    ["wh2_main_skv_queek_headtaker-srw_skv_stormvermin"] = -2,
    ["wh2_main_skv_lord_skrolk-srw_catapults"] = -2,
    ["wh2_main_skv_lord_skrolk-srw_skv_plague_monks"] = -2,
    ["wh2_dlc12_skv_ikit_claw-srw_skv_ratlings"] = -2,
    ["wh2_dlc12_skv_ikit_claw-srw_skv_jezzails"] = -2,
    ["wh2_dlc12_skv_ikit_claw-srw_skv_warpfire_thrower"] = -2,
    ["wh2_dlc12_skv_ikit_claw-srw_skv_stormfiend"] = -1,
    ["wh2_dlc14_skv_deathmaster_snikch-srw_skv_missile_runners"] = -2,
    ["wh2_dlc16_skv_throt_the_unclean-srw_skv_ratogres"] = -2,
    ["wh2_dlc16_skv_throt_the_unclean-srw_skv_abomination"] = -2,
    ["wh2_dlc16_skv_throt_the_unclean-srw_skv_brood_horror"] = -2,
    ["wh2_dlc16_skv_throt_the_unclean-srw_skv_stormfiend"] = -1,
    ["wh2_dlc16_skv_throt_the_unclean-srw_skv_monsters"] = -2,
    --clans
    ["Thom_vulkan_moltskin_searflesh-srw_skv_warpfire_thrower"] = -2,
    ["skv_feskit-srw_skv_stormvermin"] = -2,
    ["liger_skv_skretch-srw_skv_ratlings"] = -1,
    ["liger_skv_skretch-srw_skv_jezzails"] = -1,
    ["liger_skv_skretch-srw_skv_warpfire_thrower"] = -1,
    ["liger_skv_skretch-srw_skv_globadiers"] = -1,
    ["liger_skv_skretch-srw_skv_warp_grinder"] = -1,
    ["liger_skv_skretch-srw_skv_mortars"] = -1,
    ["liger_skv_skretch-srw_skv_catapults"] = -2,
    ["liger_skv_skretch-srw_skv_lightning"] = -2,
    ["liger_skv_skretch-srw_skv_artillery"] = -2,
    ["clan_vrritkin_lord_trikstab-srw_all_artillery"] = -2,
    ["clan_vrritkin_lord_trikstab-srw_skv_artillery"] = -2,
    ["clan_vrritkin_lord_trikstab-srw_skv_lightning"] = -2,
    ["clan_vrritkin_lord_trikstab-srw_skv_catapults"] = -2,
    ["clan_vrritkin_lord_trikstab-srw_skv_globadiers"] = -2,
    ["clan_vrritkin_lord_trikstab-srw_skv_mortars"] = -2,
    ["clan_vrritkin_lord_trikstab-srw_skv_neck_cutters"] = -2,
  --lizarmen
    ["wh2_main_lzd_kroq_gar-srw_lzd_saurus"] = -2,
    ["wh2_main_lzd_kroq_gar-srw_lzd_cold_one"] = -2,
    ["wh2_main_lzd_lord_mazdamundi-srw_lzd_temple_guards"] = -2,
    ["wh2_dlc12_lzd_tiktaqto-srw_lzd_coatl"] = -2,
    ["wh2_dlc12_lzd_tiktaqto-srw_lzd_ripperdactyl"] = -2,
    ["wh2_dlc12_lzd_tiktaqto-srw_lzd_teranodons"] = -2,
    ["lzd_tetto_eko-srw_lzd_salamanders"] = -2,
    ["wh2_dlc13_lzd_gor_rok-srw_lzd_saurus"] = -2,
    ["wh2_dlc13_lzd_nakai-srw_lzd_kroxigors"] = -2,
  --vcoast
    ["wh2_dlc11_cst_cylostra-srw_cst_mournguls"] = -2,
    ["wh2_dlc11_cst_cylostra-srw_cst_syreens"] = -2,
    ["wh2_dlc11_cst_noctilus-srw_cst_necrofex"] = -2,
  --mods
    ["arb_fatandira-srw_nomad"] = -2,
    ["arb_golden_magus-srw_genie"] = -2,
    ["arb_golden_magus-srw_carpet"] = -2,
    ["roy_ogr_slaughtermaster-srw_ogres"] = -1,
    ["roy_ogr_tyrant-srw_ogres"] = -1,

}