Supply_lines_rework.group_discount = {
  --empire
    ["emp_karl_franz-greatswords"] = -2,
    ["emp_karl_franz-greatswords_ror"] = -2,
    ["emp_karl_franz-reiksguard"] = -2,
    ["emp_karl_franz-reiksguard_ror"] = -2,
    ["wh2_dlc13_emp_cha_markus_wulfhart_0-huntsmen"] = -2,
    ["wh2_dlc13_emp_cha_markus_wulfhart_0-huntsmen_ror"] = -2,
    ["dlc04_emp_volkmar-knights_emp"] = -2,
    ["dlc04_emp_volkmar-free_company_ror"] = -2,
    ["dlc04_emp_volkmar-flagellants_ror"] = -2,
    ["emp_balthasar_gelt-artillery_ror"] = -1,
    ["emp_balthasar_gelt-artillery"] = -1,
    ["emp_balthasar_gelt-artillery_wagon"] = -1,
  --dwarfs
    ["dwf_ungrim_ironfist-slayers"] = -2,
    ["dwf_thorgrim_grudgebearer-longbeards"] = -2,
    ["dwf_thorgrim_grudgebearer-hammerers"] = -2,
    ["wh2_dlc17_dwf_thorek-artillery_classic"] = -2,
    ["wh2_dlc17_dwf_thorek-quarrellers"] = -2,
  --greekskins
    ["grn_grimgor_ironhide-black_orcs"] = -2,
    ["grn_grimgor_ironhide-big_uns"] = -2,
    ["grn_grimgor_ironhide-big_uns_boar"] = -2,
    ["grn_azhag_the_slaughterer-wyverns"] = -2,
    ["dlc06_grn_skarsnik-night_goblins"] = -2,
    ["dlc06_grn_skarsnik-goblins"] = -2,
    ["dlc06_grn_skarsnik-goblin_spider"] = -2,
    ["dlc06_grn_wurrzag_da_great_prophet-savage"] = -2,
    ["dlc06_grn_wurrzag_da_great_prophet-savage_boar"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-wagon"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-goblins"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-goblin_spider"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-big_uns_boar"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-savage_boar"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-savage"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-big_uns"] = -2,
    ["wh2_dlc15_grn_goblin_great_shaman_raknik-goblin_spider"] = -2,
    ["wh2_dlc15_grn_goblin_great_shaman_raknik-arachnaroks"] = -2,
    
}