Supply_lines_rework.group_discount = {
  --empire
    ["emp_karl_franz-greatswords"] = -2,
    ["emp_karl_franz-greatswords_ror"] = -2,
    ["emp_karl_franz-reiksguard"] = -2,
    ["emp_karl_franz-reiksguard_ror"] = -2,
    ["wh2_dlc13_emp_cha_markus_wulfhart_0-huntsmen"] = -2,
    ["wh2_dlc13_emp_cha_markus_wulfhart_0-huntsmen_ror"] = -2,
    ["dlc04_emp_volkmar-knights_emp"] = -2,
    ["dlc04_emp_volkmar-free_company_ror"] = -2,
    ["dlc04_emp_volkmar-flagellants_ror"] = -2,
    ["emp_balthasar_gelt-artillery_ror"] = -1,
    ["emp_balthasar_gelt-artillery"] = -1,
    ["emp_balthasar_gelt-artillery_wagon"] = -1,
    --cult of ulric
    ["ulric_grandmaster-knight_white_wolf"] = -2,
    ["ulric_grandmaster-knight_white_wolf_ror"] = -2,
    ["ulric_ar_ulric-ulric_cult"] = -2,
    ["ulric_ar_ulric-ulric_cult_ror"] = -2,
    ["ulric_ar_ulric-knight_white_wolf_ror"] = -2,
    ["ulric_ar_ulric-knight_white_wolf"] = -2,
    --mixu
    ["emp_marius_leitdorf-knights_emp"] = -2,
    ["emp_marius_leitdorf-blazing_sun"] = -2,
    ["emp_marius_leitdorf-reiksguard"] = -2,
    ["emp_marius_leitdorf-reiksguard_ror"] = -2,
    ["emp_wolfram_hertwig-knights_emp"] = -2,
    ["emp_wolfram_hertwig-blazing_sun"] = -2,
    ["emp_wolfram_hertwig-reiksguard"] = -2,
    ["emp_wolfram_hertwig-reiksguard_ror"] = -2,
    ["emp_aldebrand_ludenhof-handgunners"] = -2,
    ["emp_aldebrand_ludenhof-handgunners_ror"] = -2,
    ["emp_aldebrand_ludenhof-elite_hangunners_ror"] = -2,
    ["emp_aldebrand_ludenhof-elite_hangunners"] = -2,
    ["dlc03_emp_boris_todbringer-halberdiers"] = -2,
    ["dlc03_emp_boris_todbringer-handgunners"] = -2,
    ["dlc03_emp_boris_todbringer-handgunners_ror"] = -2,
    ["emp_theoderic_gausser-free_company"] = -2,
    ["emp_theoderic_gausser-free_company_ror"] = -2,
    ["emp_valmir_von_raukov-halberdiers"] = -2,
    ["emp_valmir_von_raukov-spearmen"] = -2,
    ["emp_alberich_haupt_anderssen-huntsmen"] = -2,
    ["emp_alberich_haupt_anderssen-huntsmen_ror"] = -2,
    ["emp_helmut_feuerbach-taal_cult"] = -2,
    ["emp_helmut_feuerbach-rhya"] = -2,
    --all ror
    ["emp_edward_van_der_kraal-ror"] = -2,
    ["emp_edward_van_der_kraal-artillery_wagon_ror"] = -2,
    ["emp_edward_van_der_kraal-artillery_ror"] = -2,
    ["emp_edward_van_der_kraal-demigryph_ror"] = -2,
    ["emp_edward_van_der_kraal-flagellants_ror"] = -2,
    ["emp_edward_van_der_kraal-free_company_ror"] = -2,
    ["emp_edward_van_der_kraal-greatswords_ror"] = -2,
    ["emp_edward_van_der_kraal-handgunners_ror"] = -2,
    ["emp_edward_van_der_kraal-elite_hangunners_ror"] = -2,
    ["emp_edward_van_der_kraal-huntsmen_ror"] = -2,
    ["emp_edward_van_der_kraal-magic_machine_ror"] = -2,
    ["emp_edward_van_der_kraal-reiksguard_ror"] = -2,
    ["emp_edward_van_der_kraal-swordsmen_ror"] = -2,
    ["emp_edward_van_der_kraal-knight_white_wolf"] = -2,
    ["emp_edward_van_der_kraal-knight_white_wolf_ror"] = -2,
  --dwarfs
    ["dwf_ungrim_ironfist-slayers"] = -2,
    ["dwf_thorgrim_grudgebearer-longbeards"] = -2,
    ["dwf_thorgrim_grudgebearer-hammerers"] = -2,
    ["wh2_dlc17_dwf_thorek-artillery_classic"] = -2,
    ["wh2_dlc17_dwf_thorek-quarrellers"] = -2,
    --mods
    ["wh_main_dwf_cha_greybeard-flying_machine"] = -2,
    ["wh_main_dwf_cha_greybeard-land_machine"] = -2,
    ["dwf_kraka_drak-huskarls"] = -2,
    ["dwf_sven_hasselfriesian-warriors"] = -2,
    ["dwf_sven_hasselfriesian-artillery_classic"] = -2,
    ["dwf_sven_hasselfriesian-artillery_gun"] = -2,
    ["dwf_sven_hasselfriesian-artillery_fire"] = -2,
    ["dwf_alrik_ranulfsson-longbeards"] = -2,
    ["dwf_brokk_ironpick-irondrakes"] = -2,
    ["dwf_brokk_ironpick-flying_machine"] = -2,
    ["dwf_brokk_ironpick-artillery_fire"] = -2,
    ["dwf_rorek_granitehand-ironbreakers"] = -2,
    ["dwf_rorek_granitehand-miners"] = -2,
    ["dwf_kazador_dragonslayer-ironbreakers"] = -2,
    ["dwf_kazador_dragonslayer-miners"] = -2,
    ["dwf_bloodline_grimm_burloksson-flying_machine"] = -2,

  --greekskins
    ["grn_grimgor_ironhide-black_orcs"] = -2,
    ["grn_grimgor_ironhide-big_uns"] = -2,
    ["grn_grimgor_ironhide-big_uns_boar"] = -2,
    ["grn_azhag_the_slaughterer-wyverns"] = -2,
    ["dlc06_grn_skarsnik-night_goblins"] = -2,
    ["dlc06_grn_skarsnik-goblins"] = -2,
    ["dlc06_grn_skarsnik-goblin_spider"] = -2,
    ["dlc06_grn_skarsnik-goblin_wolves"] = -2,
    ["dlc06_grn_wurrzag_da_great_prophet-savage"] = -2,
    ["dlc06_grn_wurrzag_da_great_prophet-savage_boar"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-wagon"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-goblins"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-goblin_spider"] = -2,
    ["wh2_dlc15_grn_grom_the_paunch-goblin_wolves"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-big_uns_boar"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-savage_boar"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-savage"] = -2,
    ["wh2_dlc15_grn_orc_warboss_oglok-big_uns"] = -2,
    ["wh2_dlc15_grn_goblin_great_shaman_raknik-goblin_spider"] = -2,
    ["wh2_dlc15_grn_goblin_great_shaman_raknik-arachnaroks"] = -2,
    --mods
    ["grn_gorbad_ironclaw-big_uns_boar"] = -2,
    ["grn_gorbad_ironclaw-big_uns"] = -2,
    ["ws_grn_grak_beastbasha-arachnaroks"] = -2,
    ["ws_grn_grak_beastbasha-giants"] = -2,
    ["ws_grn_grak_beastbasha-idols"] = -2,
    ["ws_grn_grak_beastbasha-other_monsters"] = -2,
    ["ws_grn_grak_beastbasha-wyverns"] = -2,
    ["ws_grn_grak_beastbasha-trolls"] = -2,
    ["ws_grn_grak_beastbasha-savage"] = -2,
    ["ws_grn_grak_beastbasha-hydra"] = -2,
    ["ws_grn_grak_beastbasha-savage_boar"] = -2,
    ["grn_gorfang_rotgut-big_uns_boar"] = -2,
    ["grn_gorfang_rotgut-big_uns"] = -2,
    ["grn_gorfang_rotgut-chariots"] = -2,

  --vcounts
    ["vmp_mannfred_von_carstein-black_knights"] = -2,
    ["dlc04_vmp_helman_ghorst-grave_guard"] = -2,
    ["pro02_vmp_isabella_von_carstein-vampiress"] = -2,
    ["wh2_dlc11_vmp_bloodline_lahmian-lahmian"] = -2,
  --norsca
    ["wh_dlc08_nor_wulfrik-marauders"] = -2,
    ["wh_dlc08_nor_wulfrik-berserkers"] = -2,
    ["wh_dlc08_nor_wulfrik-mammoths"] = -2,
    ["wh_dlc08_nor_throgg-trolls"] = -2,
    ["nor_egil_styrbjorn-berserkers"] = -2,
    ["nor_egil_styrbjorn-skinwolves"] = -2,
    ["thm_skeggi_losterikson-marauders"] = -2,
    ["thm_skeggi_losterikson-dinos"] = -2,
    
  --wood elves
    ["dlc05_wef_orion-stag_cav"] = -2,
    ["dlc05_wef_durthu-trees"] = -2,
    ["wh2_dlc16_wef_sisters_of_twilight-archers"] = -2,
    ["wh2_dlc16_wef_sisters_of_twilight-dragons"] = -2,
    ["wh2_dlc16_wef_sisters_of_twilight-hawks"] = -2,
    ["wh2_dlc16_wef_drycha-trees"] = -2,
    --mixu
    ["wef_wychwethyl-wardancers"] = -2,
  --hight elves
    ["wh2_main_hef_tyrion-archers"] = -2,
    ["wh2_main_hef_tyrion-spearmen"] = -2,
    ["wh2_main_hef_tyrion-swordsmen"] = -2,
    ["wh2_main_hef_tyrion-sea_guard"] = -1,
    ["wh2_main_hef_tyrion-silver_helms"] = -2,
    ["wh2_dlc10_hef_alith_anar-stealth_archers"] = -2,
    ["wh2_main_hef_prince_alastar-lions"] = -2,
    ["wh2_main_hef_prince_alastar-lion_chariots"] = -2,
    ["wh2_dlc10_hef_alarielle-avelorn"] = -2,
    ["wh2_main_hef_teclis-phoenixes"] = -2,
    ["wh2_main_hef_teclis-swordmasters"] = -2,
    ["wh2_dlc15_hef_imrik-dragon_princes"] = -2,
    ["wh2_dlc15_hef_imrik-dragons"] = -2,
    ["wh2_dlc15_hef_eltharion-mistwalkers"] = -2,
    --mods
    ["hef_korhil-lions"] = -2,
    ["hef_korhil-lion_chariots"] = -2,
    ["hef_belannaer-swordmasters"] = -2,
    ["hef_bloodline_caradryan-phoenixes"] = -2,
    ["hef_bloodline_caradryan-phoenix_guard"] = -2,
    ["AK_aislinn-sea_company"] = -2,
    ["AK_aislinn-sea_guard"] = -2,

  --dark elves
    ["wh2_main_def_malekith-black_guard"] = -2,
    ["wh2_main_def_malekith-darkshards"] = -2,
    ["wh2_main_def_malekith-spearmen"] = -2,
    ["wh2_dlc11_def_lokhir-corsairs"] = -2,
    ["wh2_dlc10_def_crone_hellebron-witch_elves"] = -2,
    ["wh2_dlc10_def_crone_hellebron-sisters"] = -2,
    ["wh2_dlc14_def_malus_darkblade-cold_one_chariot"] = -2,
    ["wh2_dlc14_def_malus_darkblade-cold_one"] = -2,
    ["wh2_twa03_def_rakarth-dragons"] = -2,
    ["wh2_twa03_def_rakarth-hydra"] = -2,
    ["wh2_twa03_def_rakarth-monsters"] = -2,
    ["wh2_twa03_def_rakarth-medusa"] = -2,
    --mods
    ["def_tullaris_dreadbringer-witch_elves"] = -2,
    ["def_tullaris_dreadbringer-executioners"] = -2,
    ["volilosh-darkshards"] = -2,
    ["volilosh-shades"] = -2,
    ["def_hag_queen_malida-witch_elves"] = -2,
  --skaven
    ["wh2_main_skv_queek_headtaker-stormvermin"] = -2,
    ["wh2_main_skv_lord_skrolk-catapults"] = -2,
    ["wh2_main_skv_lord_skrolk-plague_monks"] = -2,
    ["wh2_dlc12_skv_ikit_claw-ratlings"] = -2,
    ["wh2_dlc12_skv_ikit_claw-jezzails"] = -2,
    ["wh2_dlc12_skv_ikit_claw-warpfire_thrower"] = -2,
    ["wh2_dlc12_skv_ikit_claw-stormfiend"] = -1,
    ["wh2_dlc14_skv_deathmaster_snikch-missile_runners"] = -2,
    ["wh2_dlc16_skv_throt_the_unclean-rat_ogres"] = -2,
    ["wh2_dlc16_skv_throt_the_unclean-abomination"] = -2,
    ["wh2_dlc16_skv_throt_the_unclean-brood_horror"] = -2,
    ["wh2_dlc16_skv_throt_the_unclean-stormfiend"] = -1,
    ["wh2_dlc16_skv_throt_the_unclean-monsters"] = -1,
    --clans
    ["Thom_vulkan_moltskin_searflesh-warpfire_thrower"] = -2,
    ["skv_feskit-stormvermin"] = -2,
    ["liger_skv_skretch-ratlings"] = -1,
    ["liger_skv_skretch-jezzails"] = -1,
    ["liger_skv_skretch-warpfire_thrower"] = -1,
    ["liger_skv_skretch-globadiers"] = -1,
    ["liger_skv_skretch-warp_grinder"] = -1,
    ["liger_skv_skretch-mortars"] = -1,
    ["liger_skv_skretch-art_catapults"] = -2,
    ["liger_skv_skretch-art_lightning"] = -2,
    ["liger_skv_skretch-art_other"] = -2,
    ["clan_vrritkin_lord_trikstab-artillery"] = -2,
    ["clan_vrritkin_lord_trikstab-art_other"] = -2,
    ["clan_vrritkin_lord_trikstab-art_lightning"] = -2,
    ["clan_vrritkin_lord_trikstab-art_catapults"] = -2,
    ["clan_vrritkin_lord_trikstab-globadiers"] = -2,
    ["clan_vrritkin_lord_trikstab-mortars"] = -2,
    ["clan_vrritkin_lord_trikstab-neck_cutters"] = -2,
  --lizarmen
    ["wh2_main_lzd_kroq_gar-saurus"] = -2,
    ["wh2_main_lzd_kroq_gar-cold_one"] = -2,
    ["wh2_main_lzd_lord_mazdamundi-temple_guards"] = -2,
    ["wh2_dlc12_lzd_tiktaqto-coatl"] = -2,
    ["wh2_dlc12_lzd_tiktaqto-ripperdactyl"] = -2,
    ["wh2_dlc12_lzd_tiktaqto-teranodons"] = -2,
    ["lzd_tetto_eko-salamanders"] = -2,
    ["wh2_dlc13_lzd_gor_rok-saurus"] = -2,
    ["wh2_dlc13_lzd_nakai-kroxigors"] = -2,
  --vcoast
    ["wh2_dlc11_cst_cylostra-mournguls"] = -2,
    ["wh2_dlc11_cst_cylostra-syreens"] = -2,
    ["wh2_dlc11_cst_noctilus-necrofex"] = -2,
  --mods
    ["arb_fatandira-nomad"] = -2,
    ["arb_golden_magus-genie"] = -2,
    ["arb_golden_magus-carpet"] = -2,
    ["roy_ogr_slaughtermaster-ogres"] = -1,
    ["roy_ogr_tyrant-ogres"] = -1,

}